---
title: "Preparing Spatial Data"
author: "Amy Zyck"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This code follows that documented by [Tom Jenkins](https://github.com/Tom-Jenkins/seascape_rda_tutorial).

```{r}
# Load packages
library(dplyr)
library(raster)
library(marmap)
library(ade4)
library(adespatial)
library(SoDA)
library(psych)
```

I created a .csv file containing latitude and longitude data for each population and can be accessed [here](https://github.com/amyzyck/EecSeq_NB_EasternOyster/blob/master/Analysis/PopGen_SeaGen_Analyses/HaplotigMasked_Genome/Outlier_SNPs/RedundancyAnalysis/input_files/coords.csv). I followed Tom Jenkins's code to [prepare spatial data](https://github.com/Tom-Jenkins/seascape_rda_tutorial/blob/master/2.Prepare_spatial_data/2.prepare_spatial_data.R).

```{r}
# Import coordinates of sites
coords = read.csv("coords.csv")
names(coords)
```


#--------------#
#
# Compute dbMEMs
#
#--------------#

# Further info on distance-based Moran's Eigenvector Maps in the vignette
# vignette("tutorial", package = "adespatial")
```{r}
# Transform geographic coordinates into cartesian coordinates
cart = geoXY(coords$Lat, coords$Lon)
```

```{r}
# Calculate euclidian distances
euclidian_distances = dist(cart, method = "euclidean") 
```

```{r}
# Compute distance-based Moran's Eigenvector Maps
dbmems = dbmem(euclidian_distances, thresh = NULL)
dbmems
```

```{r}
# Export dbMEMs
write.csv(dbmems, file = "dbmems.csv", row.names = FALSE)
```